---
title: "LT50/SC analysis"
author: "Jon Henn"
date: "May 2, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(lmerTest)
library(ggplot2)

xy <- read.csv("liana_xy.csv")
supercooling <- read.csv("liana_supercooling.csv")
PEL_lt50 <- read.csv("liana_pel_lt50.csv")
leaf_area <- read.csv("liana_leaf_area.csv")
leaf_mass <- read.csv("liana_leaf_mass.csv")
bioclim <- read.csv("liana_bioclim.csv")

supercooling <- supercooling %>% 
  mutate(sample_id = paste(population, rep, leaf, sep = "")) %>% 
  select(-13)

samples <- leaf_mass %>% 
  full_join(leaf_area) %>% 
  full_join(PEL_lt50) %>% 
  #full_join(supercooling, by = "sample_id") %>% 
  distinct(sample_id)

samples = read.csv("samples.csv") %>% 
  select(-X)



PEL <- samples %>% 
  full_join(PEL_lt50) %>% 
  full_join(leaf_mass) %>% 
  #full_join(supercooling) %>% 
  full_join(leaf_area) %>% 
  full_join(xy, by = "population") %>% 
  full_join(bioclim) %>% 
  select(-spp.x) %>% 
  filter(PEL_LT50 < 0) %>% 
  mutate(SLA = (area_cm2/(dry_mass/1000))) %>% 
  mutate(LDMC = (dry_mass/wet_mass)) %>% 
  filter(spp != "PATR") %>% 
  mutate(bio6 = (bio6-(mean(bio6)))/sd(bio6))

sc <- samples %>% 
  full_join(supercooling) %>%
  full_join(xy, by = "population") %>% 
  full_join(bioclim) %>% 
  mutate(ldmc = sc_dry_mass/sc_wet_mass) %>% 
  filter(spp != "PATR") %>% 
  filter(sc_wet_mass > 0) %>% 
  filter(spp != "VIRI") %>% 
  mutate(bio6 = (bio6-(mean(bio6)))/sd(bio6))
```

## plots!!

```{r plots,}
PEL %>% 
ggplot(aes(x = bio6, y = PEL_LT50, color = spp)) +
  geom_point(size = 2) +
  theme_classic()

sc %>% 
  filter(spp != "VIRI") %>% 
  filter(spp != "PATR") %>% 
  filter(spp != "") %>% 
  ggplot(aes(x = bio6, y = sc_temp, color = spp)) +
    geom_point(size = 2) + 
    theme_classic()

PEL %>% 
  ggplot(aes(x = bio6, y = latitude, color = spp)) +
  geom_point(size = 2) +
  theme_classic()

PEL %>% 
  ggplot(aes(x = dry_mass, y = PEL_LT50, color = spp)) +
  geom_point(size = 2) +
  theme_classic()

PEL %>% 
  ggplot(aes(x = LDMC, y = PEL_LT50, color = spp)) +
  geom_point(size = 2) +
  theme_classic()

PEL %>% 
  ggplot(aes(x = PEL_LT50, y = CorPEL_LT50, color = spp)) +
  geom_point(size = 2) +
  theme_classic()

sc %>% 
  ggplot(aes(x = sc_dry_mass, y = sc_temp))+
  geom_point(size = 2) +
  theme_classic()

sc %>% 
  ggplot(aes(x = ldmc, y = sc_temp))+
  geom_point(size = 2) +
  theme_classic()

sc %>% 
  ggplot(aes(x = fp_temp, y = sc_temp))+
  geom_point(size = 2) +
  theme_classic()

```

## models
```{r models,}
m.PEL <- lmer(PEL_LT50 ~ bio6*spp*LDMC + (1|population), data = PEL)
summary(m.PEL)
step(m.PEL)

m.PEL1 <- lmer(PEL_LT50 ~ bio6*spp + (1|population), data = PEL)
summary(m.PEL1)

m.sc <- lmer(sc_temp ~ bio6+ldmc+bio6:ldmc + (1|population), data = sc)
summary(m.sc)
step(m.sc)

m.sc1 <- lmer(sc_temp ~ bio6 + (1|population), data = sc)
summary(m.sc1)
anova(m.sc, m.sc1)
```